name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
        
    - name: Setup Android SDK
      uses: android-actions/setup-android@v3
        
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      
    - name: Update Gradle Version
      run: |
        sed -i 's/gradle-5.4.1-all.zip/gradle-6.9-all.zip/g' gradle/wrapper/gradle-wrapper.properties
        ./gradlew wrapper --gradle-version 6.9
      
    - name: Build with Gradle
      run: ./gradlew build
      
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: app-debug
        path: app/build/outputs/apk/debug/*.apk
